---
label: Default
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  description: Value = post
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
  description: Type = 2018-05-29 18:05:55
- type: file
  name: image
  label: image
- type: text
  name: tags
  label: tags
